commit_message: "[ci skip]"
files:
  - source: /app/lib/l10n/app_en.arb
    translation: /app/lib/l10n/app_%two_letters_code%.arb
  - source: /docs/i18n/en/**/*
    translation: /docs/i18n/%two_letters_code%/**/%original_file_name%
  - source: /docs/docs/**/*
    translation: /docs/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  - source: /docs/community/**/*
    ignore:
      - CHANGELOG.md
      - versions.md
    translation: /docs/i18n/%two_letters_code%/docusaurus-plugin-content-docs-community/current/**/%original_file_name%
  - source: /docs/versioned_docs/**/*
    translation: /docs/i18n/%two_letters_code%/docusaurus-plugin-content-docs/**/%original_file_name%
