name: butterfly
version: 1.1.2
summary: Change the world.
description: Butterfly is a note app where your ideas come first. You can paint, add texts and export them easily on every device. This app works on android, windows, linux and in the web.

confinement: strict
base: core18
grade: stable

slots:
  dbus-butterfly: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: dev.linwood.butterfly # adjust accordingly to your app name and
    
apps:
  butterfly:
    command: butterfly
    extensions: [flutter-beta] # Where "beta" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-butterfly
parts:
  butterfly:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
