# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

Dir.chdir("../../..") do
  platform :android do
    desc "Runs all the tests"
    lane :test do
      gradle(task: "test")
    end

    desc "Submit a new Beta Build to Crashlytics Beta"
    lane :beta do
      sh "flutter build appbundle -v --release --flavor development"
      upload_to_play_store(track: 'beta', aab: 'app/build/app/outputs/bundle/developmentRelease/app-development-release.aab', metadata_path: "app/android/fastlane/metadata")
    end

    desc "Deploy a new version to the Google Play"
    lane :deploy do
      sh "flutter build appbundle -v --release --flavor production"
      upload_to_play_store(aab: 'app/build/app/outputs/bundle/productionRelease/app-production-release.aab', metadata_path: "app/android/fastlane/metadata")
    end
  end
end
