# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    # Get version from ENV
    version = ENV['VERSION']
    changelog = "Read more at https://github.com/LinwoodCloud/Butterfly/releases"
    if !version.nil? && !version.empty?
      changelog = "Read more at https://github.com/LinwoodCloud/Butterfly/release/tag/#{version}"
    end
    upload_to_play_store(track: 'beta', 
      aab: '../build/app/outputs/bundle/release/app-release.aab', 
      json_key_data: ENV['PLAY_STORE_UPLOAD_KEY'], 
      metadata_path: '../../fastlane/metadata', changelog: changelog)
    
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    # Get version from ENV
    version = ENV['VERSION']
    changelog = "Read more at https://github.com/LinwoodCloud/Butterfly/releases"
    if !version.nil? && !version.empty?
      changelog = "Read more at https://github.com/LinwoodCloud/Butterfly/release/tag/#{version}"
    end
    gradle(task: "clean assembleRelease")
    upload_to_play_store(aab: '../build/app/outputs/bundle/release/app-release.aab', 
      json_key_data: ENV['PLAY_STORE_UPLOAD_KEY'], 
      metadata_path: '../../fastlane/metadata', changelog: changelog)
  end
end
