name: butterfly
grade: stable
adopt-info: butterfly
icon: linux/debian/usr/share/icons/hicolor/256x256/apps/dev.linwood.butterfly.png
base: core24
confinement: strict
compression: lzo
title: 'Linwood Butterfly' #For future, if changes needed, it can be easily done from here
issues: https://github.com/LinwoodDev/Butterfly/issues #for metadata
website: https://github.com/LinwoodDev/Butterfly #for metadata in gnome-software, kde-discover
license: AGPL-3.0 #for metadata
platforms:
  amd64:
  arm64:
apps:
  butterfly:
    command: butterfly
    extensions: [gnome]
    plugs:
      - home
      - network
      - optical-drive
      - removable-media
    common-id: dev.linwood.butterfly
    desktop: meta/gui/butterfly.desktop

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    #source-tag: $(curl https://raw.githubusercontent.com/LinwoodDev/Butterfly/nightly/FLUTTER_VERSION)
    plugin: nil
    override-pull: |
      set -eux
      # Extract the Flutter version from pubspec.yaml
      FLUTTER_VERSION=$(grep -E '^  flutter:' "$CRAFT_PROJECT_DIR/app/pubspec.yaml" | awk '{print $2}')
      echo "Using Flutter version: $FLUTTER_VERSION"
      git clone --recursive --branch "$FLUTTER_VERSION" https://github.com/flutter/flutter.git "$CRAFT_PART_SRC"
    override-build: |
      set -eux
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -sf $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      export PATH="$CRAFT_PART_INSTALL/usr/bin:$PATH"
      flutter doctor
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
    override-prime: ''
  butterfly:
    after: [ flutter-git ]
    plugin: nil
    #plugin: flutter
    source: .
    build-snaps:
      - cmake
    build-packages:
      - curl
      - libsecret-1-dev
      - libjsoncpp-dev
    override-build: |
      craftctl default
      set -eux
      cd $CRAFT_PART_SRC_WORK
      cd app
      flutter pub get || true
      flutter build linux --release --verbose --target lib/main.dart
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/
      mkdir -p $CRAFT_PART_INSTALL/metainfo
      cp -r linux/debian/usr/share/metainfo/dev.linwood.butterfly.appdata.xml $CRAFT_PART_INSTALL/metainfo/
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      mv linux/debian/usr/share/applications/dev.linwood.butterfly.desktop $CRAFT_PART_INSTALL/meta/gui/butterfly.desktop
      mkdir -p $CRAFT_PART_INSTALL/usr/share/icons/hicolor
      cp linux/debian/usr/share/icons/hicolor $CRAFT_PART_INSTALL/usr/share/icons/ -r
    stage-packages:
      - libsecret-1-0
      - libjsoncpp25
    parse-info: [ metainfo/dev.linwood.butterfly.appdata.xml ]
  