import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';

const offlineAppName = 'butterfly';
const workerFileName = 'flutter_service_worker.js';

Future<void> main(List<String> arguments) async {
  if (arguments.length > 1) {
    stderr.writeln(
      'Usage: dart run tools/build_web_service_worker.dart [web-build-directory]',
    );
    exitCode = 64;
    return;
  }
  final directory = arguments.isEmpty
      ? Directory.fromUri(Platform.script.resolve('../app/build/web/'))
      : Directory(arguments.single);
  try {
    final count = await buildServiceWorker(directory);
    stdout.writeln('Generated offline worker with $count resources.');
  } on FileSystemException catch (error) {
    stderr.writeln(error);
    exitCode = 1;
  } on StateError catch (error) {
    stderr.writeln(error.message);
    exitCode = 1;
  }
}

/// Run after Flutter and other tools have finished writing the web build.
Future<int> buildServiceWorker(Directory directory) async {
  final root = directory.absolute.uri;
  final files = <String, File>{};
  Future<void> walk(Directory current) async {
    await for (final entry in current.list(followLinks: false)) {
      if (entry.uri.pathSegments
          .where((part) => part.isNotEmpty)
          .last
          .startsWith('.')) {
        continue;
      }
      if (entry is Directory) {
        await walk(entry);
      } else if (entry is File) {
        final name = entry.absolute.uri.path.substring(root.path.length);
        if (name != workerFileName &&
            !name.endsWith('.map') &&
            !name.endsWith('.symbols')) {
          files[name] = entry;
        }
      }
    }
  }

  await walk(Directory.fromUri(root));
  for (final required in [
    'index.html',
    'flutter_bootstrap.js',
    'manifest.json',
  ]) {
    if (!files.containsKey(required)) {
      throw StateError('Missing web build file: $required');
    }
  }
  final bootstrap = await files['flutter_bootstrap.js']!.readAsString();
  if (!RegExp(r'"useLocalCanvasKit"\s*:\s*true').hasMatch(bootstrap)) {
    throw StateError(
      'Build with --no-web-resources-cdn so renderers are available offline.',
    );
  }
  final names = files.keys.toList()..sort();
  final template = workerTemplate.replaceAll('/* APP_NAME */', offlineAppName);
  final digest = _DigestSink();
  final hash = sha256.startChunkedConversion(digest)
    ..add(utf8.encode(template));
  for (final name in names) {
    final bytes = await files[name]!.readAsBytes();
    hash
      ..add(utf8.encode(jsonEncode([name, bytes.length])))
      ..add(bytes);
  }
  hash.close();
  final worker = template
      .replaceFirst('/* BUILD_VERSION */', jsonEncode(digest.value.toString()))
      .replaceFirst('/* BUILD_RESOURCES */', jsonEncode(names));
  await File.fromUri(root.resolve(workerFileName)).writeAsString(worker);
  return names.length;
}

class _DigestSink implements Sink<Digest> {
  late Digest value;

  @override
  void add(Digest data) => value = data;

  @override
  void close() {}
}

// Browsers execute service workers as JavaScript. Keeping the template here
// makes the build tool a single Dart script with no separate runtime template.
const workerTemplate = r'''
// Generated by build_web_service_worker.dart; served at Flutter's former worker
// URL to upgrade existing registrations without running its cleanup stub.
const BUILD_VERSION = /* BUILD_VERSION */;
const BUILD_RESOURCES = /* BUILD_RESOURCES */;
const SCOPE = self.registration.scope;
const CACHE_PREFIX = `/* APP_NAME */-offline:${SCOPE}:`;
const CACHE_NAME = CACHE_PREFIX + BUILD_VERSION;
const RESOURCES = new Set(BUILD_RESOURCES.map((path) => new URL(path, SCOPE).href));
const INDEX_URL = new URL('index.html', SCOPE).href;

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    try {
      // Cache the entire build, including lazy assets and both Wasm/JS engines.
      // A failed download leaves the previous worker and cache in place.
      for (let i = 0; i < BUILD_RESOURCES.length; i += 20) {
        await cache.addAll(BUILD_RESOURCES.slice(i, i + 20).map((path) =>
          new Request(new URL(path, SCOPE), { cache: 'reload' })
        ));
      }
    } catch (error) {
      await caches.delete(CACHE_NAME);
      throw error;
    }
    // Updates wait until all existing app tabs close, preserving open sessions.
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const name of await caches.keys()) {
      if (name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME) {
        await caches.delete(name);
      }
    }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url);
  if (!url.href.startsWith(SCOPE)) return;
  url.search = '';
  url.hash = '';
  let key = url.href;
  if (!RESOURCES.has(key)) {
    if (event.request.mode !== 'navigate') return;
    key = INDEX_URL;
  }
  event.respondWith((async () => {
    const cache = await caches.open(CACHE_NAME);
    return await cache.match(key) || fetch(event.request);
  })());
});
''';
