name: butterfly
grade: stable
version: '1.6.1'
summary: Powerful, minimalistic, cross-platform, opensource note-taking app.
description: |
  Butterfly is a note app where your ideas come first. You can paint, add texts and export them easily on every device.
base: core22
confinement: strict
compression: lzo
architectures:
  - build-on: [amd64]
    build-for: [amd64]

#slots:
  #butterfly:
    #interface: dbus
    #bus: session
    #name: dev.linwood.butterfly

apps:
  butterfly:
    command: butterfly
    extensions: [gnome]
    plugs:
      - home
      - network
      - optical-drive
      - removable-media
    common-id: dev.linwood.butterfly
    desktop: usr/share/applications/dev.linwood.butterfly.desktop

parts:
  butterfly:
    plugin: dump
    source: https://github.com/LinwoodDev/Butterfly/releases/download/v1.6.1/linwood-butterfly-linux.tar.gz
    override-build: |
      craftctl default
      chmod a+x ./butterfly
    stage-packages:
      - libsecret-1-0
      - libjsoncpp25
    parse-info: [usr/share/metainfo/dev.linwood.butterfly.appdata.xml]
