name: butterfly
grade: stable
adopt-info: butterfly
icon: app/linux/debian/usr/share/icons/hicolor/256x256/apps/dev.linwood.butterfly.png
base: core22
confinement: strict
compression: lzo
title: 'Linwood Butterfly' #For future, if changes needed, it can be easily done from here
issues: https://github.com/LinwoodDev/Butterfly/issues #for metadata
website: https://github.com/LinwoodDev/Butterfly #for metadata in gnome-software, kde-discover
license: AGPL-3.0 #for metadata
architectures:
  - build-on: amd64
  #- build-on: arm64 # try to build on arm64, as per https://github.com/flutter/flutter/issues/56992
  # cannot build for arm64, check this action for more details
  # https://github.com/soumyaDghosh/Butterfly/actions/runs/5017887799/jobs/8996588822
apps:
  butterfly:
    command: butterfly
    extensions: [gnome]
    plugs:
      - home
      - network
      - optical-drive
      - removable-media
    common-id: dev.linwood.butterfly
    desktop: meta/gui/butterfly.desktop

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    #source-tag: $(curl https://raw.githubusercontent.com/LinwoodDev/Butterfly/nightly/FLUTTER_VERSION)
    plugin: nil
    override-pull: |
      git clone --recursive --branch $(curl https://raw.githubusercontent.com/LinwoodDev/Butterfly/nightly/FLUTTER_VERSION) https://github.com/flutter/flutter.git $CRAFT_PART_SRC
    override-build: |
      set -eux
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -sf $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      export PATH="$CRAFT_PART_INSTALL/usr/bin:$PATH"
      flutter doctor
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
    override-prime: ''
  butterfly:
    after: [ flutter-git ]
    plugin: nil
    #plugin: flutter
    source: https://github.com/LinwoodDev/Butterfly.git
    source-tag: nightly
    source-subdir: app
    build-snaps:
      - cmake
    build-packages:
      - curl
      - libsecret-1-dev
      - libjsoncpp-dev
    override-pull: |
      craftctl default
      git fetch --tags
      craftctl set version=$(git tag --sort=-creatordate --list 'v*' --sort=-v:refname | head -n 1 | cut -c 2-)
    override-build: |
      craftctl default
      set -eux
      cd $CRAFT_PART_SRC_WORK
      flutter pub get || true
      flutter build linux --release --verbose --target lib/main.dart
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/
      mkdir -p $CRAFT_PART_INSTALL/metainfo
      cp -r linux/debian/usr/share/metainfo/dev.linwood.butterfly.appdata.xml $CRAFT_PART_INSTALL/metainfo/
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      mv linux/debian/usr/share/applications/dev.linwood.butterfly.desktop $CRAFT_PART_INSTALL/meta/gui/butterfly.desktop
    stage-packages:
      - libsecret-1-0
      - libjsoncpp25
    parse-info: [ metainfo/dev.linwood.butterfly.appdata.xml ]
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - butterfly
      - flutter-git
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core22
      - gnome-42-2204
      - gtk-common-themes
    override-prime: |
      set -eux
      for snap in "core22" "gnome-42-2204" "gtk-common-themes" ; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
      rm -rf $CRAFT_PRIME/usr/share/doc
