# Compress images on demand (workflow_dispatch), and at 11pm every Sunday (schedule).
# Open a Pull Request if any images can be compressed.
name: Compress Images
on:
  workflow_dispatch:
  schedule:
    - cron: "00 23 * * 0"

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: compress-images
  cancel-in-progress: false

jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@2a254d926beda392b8c36e1be95252aa3d534405 # main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
      - name: Create New Pull Request If Needed
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v8
        with:
          title: Compressed Images Nightly
          branch-suffix: timestamp
          commit-message: Compressed Images
          body: ${{ steps.calibre.outputs.markdown }}
